name: Markdown Word Counter

on: 
  push:
    branches:
      - 'feature/adding-a-md-word-counter-github-action'
  pull_request:
    branches:
      - main
      - 'feature/adding-a-md-word-counter-github-action'

jobs:
  Count-Words:
    runs-on: ubuntu-latest
    steps:
      #Check out Code      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      #Set Up Python
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      #Write Greeting to Step Summary Page
      - name: Greeting
        run: echo "## Here are the word counts for each markdown file:" >> $GITHUB_STEP_SUMMARY

      #Execute Python Script 
      - name: Execute Script
        run: python count_words_in_md.py >> $GITHUB_STEP_SUMMARY